### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by LucasTMP** [LucasTMP/template_api_validator#6]
Todo list:

- [x] Github Actions
- [x] Health Cheks
- [x] UI Health app
- [x] Midleware Exception
- [ ] Controllers
- [x] Swagger
- [x] Validator Filter
- [x] Config Swagger
- [ ] DTO Validations with fluentvalidations
- [ ] Dtos
- [ ] Resources/Messages (classe estática para armazenar as mensagens de validação e outras mensagens padrões da aplicação)
- [x] EF core inmemory/local
- [x] Generic Repository
- [ ] Repositorys
- [ ] Services
- [x] CorrelateId
- [x] Base Service
- [x] Serilog
- [x] Pattern Notification
- [x] Migrations
- [x] ContextDb
